// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: OrganizationManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=manager_mock.go -package=idp . OrganizationManagerInterface
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationManagerInterface is a mock of OrganizationManagerInterface interface.
type MockOrganizationManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockOrganizationManagerInterfaceMockRecorder is the mock recorder for MockOrganizationManagerInterface.
type MockOrganizationManagerInterfaceMockRecorder struct {
	mock *MockOrganizationManagerInterface
}

// NewMockOrganizationManagerInterface creates a new mock instance.
func NewMockOrganizationManagerInterface(ctrl *gomock.Controller) *MockOrganizationManagerInterface {
	mock := &MockOrganizationManagerInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationManagerInterface) EXPECT() *MockOrganizationManagerInterfaceMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationManagerInterface) CreateOrganization(ctx context.Context, config *OrganizationConfig) (*BreakGlassCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, config)
	ret0, _ := ret[0].(*BreakGlassCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationManagerInterfaceMockRecorder) CreateOrganization(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationManagerInterface)(nil).CreateOrganization), ctx, config)
}

// DeleteOrganizationRealm mocks base method.
func (m *MockOrganizationManagerInterface) DeleteOrganizationRealm(ctx context.Context, organizationName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganizationRealm", ctx, organizationName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganizationRealm indicates an expected call of DeleteOrganizationRealm.
func (mr *MockOrganizationManagerInterfaceMockRecorder) DeleteOrganizationRealm(ctx, organizationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationRealm", reflect.TypeOf((*MockOrganizationManagerInterface)(nil).DeleteOrganizationRealm), ctx, organizationName)
}
