// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: ProjectGroupManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=resource_manager_mock.go -package=idp . ProjectGroupManagerInterface
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectGroupManagerInterface is a mock of ProjectGroupManagerInterface interface.
type MockProjectGroupManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectGroupManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectGroupManagerInterfaceMockRecorder is the mock recorder for MockProjectGroupManagerInterface.
type MockProjectGroupManagerInterfaceMockRecorder struct {
	mock *MockProjectGroupManagerInterface
}

// NewMockProjectGroupManagerInterface creates a new mock instance.
func NewMockProjectGroupManagerInterface(ctrl *gomock.Controller) *MockProjectGroupManagerInterface {
	mock := &MockProjectGroupManagerInterface{ctrl: ctrl}
	mock.recorder = &MockProjectGroupManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectGroupManagerInterface) EXPECT() *MockProjectGroupManagerInterfaceMockRecorder {
	return m.recorder
}

// AddUserToGroupByID mocks base method.
func (m *MockProjectGroupManagerInterface) AddUserToGroupByID(ctx context.Context, tenant, username, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroupByID", ctx, tenant, username, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroupByID indicates an expected call of AddUserToGroupByID.
func (mr *MockProjectGroupManagerInterfaceMockRecorder) AddUserToGroupByID(ctx, tenant, username, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroupByID", reflect.TypeOf((*MockProjectGroupManagerInterface)(nil).AddUserToGroupByID), ctx, tenant, username, groupID)
}

// AddUserToProjectGroup mocks base method.
func (m *MockProjectGroupManagerInterface) AddUserToProjectGroup(ctx context.Context, tenant, projectName, username, groupType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToProjectGroup", ctx, tenant, projectName, username, groupType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToProjectGroup indicates an expected call of AddUserToProjectGroup.
func (mr *MockProjectGroupManagerInterfaceMockRecorder) AddUserToProjectGroup(ctx, tenant, projectName, username, groupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToProjectGroup", reflect.TypeOf((*MockProjectGroupManagerInterface)(nil).AddUserToProjectGroup), ctx, tenant, projectName, username, groupType)
}

// CreateProjectGroups mocks base method.
func (m *MockProjectGroupManagerInterface) CreateProjectGroups(ctx context.Context, tenant, projectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProjectGroups", ctx, tenant, projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProjectGroups indicates an expected call of CreateProjectGroups.
func (mr *MockProjectGroupManagerInterfaceMockRecorder) CreateProjectGroups(ctx, tenant, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectGroups", reflect.TypeOf((*MockProjectGroupManagerInterface)(nil).CreateProjectGroups), ctx, tenant, projectName)
}

// DeleteProjectGroups mocks base method.
func (m *MockProjectGroupManagerInterface) DeleteProjectGroups(ctx context.Context, tenant, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectGroups", ctx, tenant, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectGroups indicates an expected call of DeleteProjectGroups.
func (mr *MockProjectGroupManagerInterfaceMockRecorder) DeleteProjectGroups(ctx, tenant, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectGroups", reflect.TypeOf((*MockProjectGroupManagerInterface)(nil).DeleteProjectGroups), ctx, tenant, projectName)
}

// RemoveUserFromProjectGroup mocks base method.
func (m *MockProjectGroupManagerInterface) RemoveUserFromProjectGroup(ctx context.Context, tenant, projectName, username, groupType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromProjectGroup", ctx, tenant, projectName, username, groupType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromProjectGroup indicates an expected call of RemoveUserFromProjectGroup.
func (mr *MockProjectGroupManagerInterfaceMockRecorder) RemoveUserFromProjectGroup(ctx, tenant, projectName, username, groupType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromProjectGroup", reflect.TypeOf((*MockProjectGroupManagerInterface)(nil).RemoveUserFromProjectGroup), ctx, tenant, projectName, username, groupType)
}
